[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "RMCVKYD-LK80402"
user = "TULIPRAAJ007"
password = "**Tulipraaj007**"
